# Dependencies
markdown:   kramdown

#Setup
title:      'UTAText: The Open Source UTAU Textbook'
url:        https://github.com/VocAddict/UTAText
home:       https://utatext.voxil.net
origin:     https://utatext.voxil.net/downloads

author: 
  name:     VocAddict
  url:      https://github.com/VocAddict

paginate:   5

#Current Version
version:    0.1

bookviewer: https://philschatz.com/book-viewer
